/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.fight;

import main.mainFrame;
import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
import logic.DropItemAfterDefeatMonster;
import java.util.Random;
import model.Player;
import model.Monster;

public class FightLevel4 extends javax.swing.JPanel {

    private mainFrame mainFrame;
    private Player player;
    private Monster monster;
    private boolean finished = false;
    private Random rand = new Random();
    private int stage = 1; // 1 = Keroco, 2 = Boss

    /**
     * Creates new form FightLevel1
     */
    public FightLevel4(mainFrame mainFrame, Player player, Monster monster) {
        this.mainFrame = mainFrame;
        this.player = player;
        this.monster = monster;
        initComponents();

        this.finished = false;
        updateHpLabels();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAttck = new javax.swing.JButton();
        btnDeff = new javax.swing.JButton();
        PlayerHP = new javax.swing.JLabel();
        PlayerHP1 = new javax.swing.JLabel();
        PlayerArmor = new javax.swing.JLabel();
        bgKroco = new javax.swing.JLabel();
        bgBos = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAttck.setBorder(javax.swing.BorderFactory.createTitledBorder("ATTACK"));
        btnAttck.setBorderPainted(false);
        btnAttck.setContentAreaFilled(false);
        btnAttck.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAttck.setPreferredSize(new java.awt.Dimension(120, 40));
        btnAttck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAttckActionPerformed(evt);
            }
        });
        add(btnAttck, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 480, 110, 100));

        btnDeff.setBorder(javax.swing.BorderFactory.createTitledBorder("DEFFENSE"));
        btnDeff.setBorderPainted(false);
        btnDeff.setContentAreaFilled(false);
        btnDeff.setPreferredSize(new java.awt.Dimension(120, 40));
        btnDeff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeffActionPerformed(evt);
            }
        });
        add(btnDeff, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 450, 80, 80));

        PlayerHP.setForeground(new java.awt.Color(255, 255, 255));
        PlayerHP.setText("HP Kamu : ");
        add(PlayerHP, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 6, -1, -1));

        PlayerHP1.setForeground(new java.awt.Color(255, 255, 255));
        PlayerHP1.setText("Monster HP :");
        add(PlayerHP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(606, 6, -1, -1));

        PlayerArmor.setForeground(new java.awt.Color(255, 255, 255));
        PlayerArmor.setText("Armor :");
        add(PlayerArmor, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 28, -1, -1));

        bgKroco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/images/fightbg/LEVEL 4 KROCO 2.png"))); // NOI18N
        add(bgKroco, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        bgBos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/images/fightbg/LEVEL 4(1).png"))); // NOI18N
        add(bgBos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeffActionPerformed
        if (player == null || monster == null) return;

        performPlayerAction(false);
        updateHpLabels();

        if (finished) {
            if (mainFrame != null) {
                mainFrame.showPanel(new ui.map.mapPanel(mainFrame));
            }
        }
    }//GEN-LAST:event_btnDeffActionPerformed

    private void btnAttckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAttckActionPerformed
        // TODO add your handling code here:
                if (player == null || monster == null) return;

        performPlayerAction(true);
        updateHpLabels();

        if (finished) {
            if (mainFrame != null) {
                mainFrame.showPanel(new ui.map.mapPanel(mainFrame));
            }
        }
    }//GEN-LAST:event_btnAttckActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel PlayerArmor;
    private javax.swing.JLabel PlayerHP;
    private javax.swing.JLabel PlayerHP1;
    private javax.swing.JLabel bgBos;
    private javax.swing.JLabel bgKroco;
    private javax.swing.JButton btnAttck;
    private javax.swing.JButton btnDeff;
    // End of variables declaration//GEN-END:variables

    private void updateHpLabels() {
        final String pText = (player != null) ? "HP Kamu: " + player.getHp() : "HP Kamu: -";
        final String mText = (monster != null) ? "HP " + monster.getName() + ": " + monster.getHp() : "HP Monster: -";
        final String aText = (player != null) ? "Armor: " + (player.getEquippedArmor() != null ? player.getEquippedArmor().getName() : "-") : "Armor: -";
        if (javax.swing.SwingUtilities.isEventDispatchThread()) {
            PlayerHP.setText(pText);
            PlayerArmor.setText(aText);
            PlayerHP1.setText(mText);
            PlayerHP.revalidate(); PlayerHP.repaint();
            PlayerArmor.revalidate(); PlayerArmor.repaint();
            PlayerHP1.revalidate(); PlayerHP1.repaint();
        } else {
            javax.swing.SwingUtilities.invokeLater(() -> {
                PlayerHP.setText(pText);
                PlayerArmor.setText(aText);
                PlayerHP1.setText(mText);
                PlayerHP.revalidate(); PlayerHP.repaint();
                PlayerArmor.revalidate(); PlayerArmor.repaint();
                PlayerHP1.revalidate(); PlayerHP1.repaint();
            });
        }
    }

    private void performPlayerAction(boolean attack) {
        if (finished) return;

        boolean monsterAttack = rand.nextBoolean();

        if (attack && monsterAttack) {
            monster.setHp(monster.getHp() - player.getAttack());
            applyDamageToPlayer(monster.getAttack());
        } else if (attack && !monsterAttack) {
            monster.setHp(monster.getHp() - player.getAttack());
        } else if (!attack && monsterAttack) {
            applyDamageToPlayer(monster.getAttack() / 2);
        } else {
            // both defend; nothing happens
        }

        if (!player.isAlive() || !monster.isAlive()) {
            finished = true;
            if (player.isAlive()) {
                // Only restore HP when the entire fight finishes (after boss is defeated)
                if (stage != 1) {
                    player.restoreFullHp();
                    updateHpLabels();
                }

                java.util.List<Object> drops = DropItemAfterDefeatMonster.dropItems(player);
                if (drops != null && !drops.isEmpty()) {
                    String[] options = new String[drops.size()];
                    for (int i = 0; i < drops.size(); i++) {
                        Object it = drops.get(i);
                        if (it instanceof model.Weapon) {
                            model.Weapon w = (model.Weapon) it;
                            options[i] = "Weapon: " + w.getName() + " (+" + w.getAttack() + " atk)";
                        } else if (it instanceof model.Armor) {
                            model.Armor a = (model.Armor) it;
                            options[i] = "Armor: " + a.getName() + " (+" + a.getDefense() + " HP)";
                        } else {
                            options[i] = it.toString();
                        }
                    }
                    int choice = JOptionPane.showOptionDialog(this, "Pilih satu item yang ingin kamu ambil:", "Item Drop",
                            JOptionPane.DEFAULT_OPTION, JOptionPane.PLAIN_MESSAGE, null, options, options[0]);

                    if (choice >= 0 && choice < drops.size()) {
                        Object chosen = drops.get(choice);
                        player.addItem(chosen);
                        if (chosen instanceof model.Weapon) {
                            model.Weapon w = (model.Weapon) chosen;
                            JOptionPane.showMessageDialog(this, "Mendapatkan " + w.getName() + "! Masuk inventory.");
                        } else if (chosen instanceof model.Armor) {
                            model.Armor a = (model.Armor) chosen;
                            JOptionPane.showMessageDialog(this, "Mendapatkan " + a.getName() + "! Masuk inventory.");
                        } else {
                            JOptionPane.showMessageDialog(this, "Mendapatkan item! Masuk inventory.");
                        }
                        updateHpLabels();
                    }
                }

                if (stage == 1) {
                    stage = 2;
                    finished = false;
                    monster = new Monster("Dragon King", 180, 22, 14);
                    JOptionPane.showMessageDialog(this, "Young Dragon dikalahkan! Dragon King muncul!");
                    updateHpLabels();
                    bgBos.setVisible(true);
                    bgKroco.setVisible(false);
                } else {
                    if (mainFrame != null) {
                        if (player != null) player.unlockLevel(5);
                        JOptionPane.showMessageDialog(this, "Selamat! Level 5 terbuka.");
                        mainFrame.showPanel(new ui.map.mapPanel(mainFrame));
                    }
                }
            }
            else {
                // player lost
                player.setMaxHp(100);
                player.restoreFullHp();
                updateHpLabels();
                JOptionPane.showMessageDialog(this, "Kamu kalah. HP direset", "Kalah", JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }

    private void applyDamageToPlayer(int dmg) {
        if (player == null || dmg <= 0) return;
        // armor/defense removed, apply damage directly
        player.takeDamage(dmg);
    }

}
