/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.fight;

import main.mainFrame;
import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
import logic.DropItemAfterDefeatMonster;
import java.util.Random;
import model.Player;
import model.Monster;
import ui.dialog.FightDialog;

public class FightLevel6 extends javax.swing.JPanel {

    private mainFrame mainFrame;
    private Player player;
    private Monster monster;
    private boolean finished = false;
    private Random rand = new Random();
    private int stage = 1; // 1 = Keroco, 2 = Boss

    /**
     * Creates new form FightLevel1
     */
    public FightLevel6(mainFrame mainFrame, Player player, Monster monster) {
        this.mainFrame = mainFrame;
        this.player = player;
        this.monster = monster;
        initComponents();

        this.finished = false;
        updateHpLabels();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAttck = new javax.swing.JButton();
        btnDeff = new javax.swing.JButton();
        PlayerHP = new javax.swing.JLabel();
        PlayerArmor = new javax.swing.JLabel();
        PlayerHP1 = new javax.swing.JLabel();

        btnAttck.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/images/iconbutton/AttackButton.png"))); // NOI18N
        btnAttck.setBorder(javax.swing.BorderFactory.createTitledBorder("ATTACK"));
        btnAttck.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAttck.setPreferredSize(new java.awt.Dimension(120, 40));
        btnAttck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAttckActionPerformed(evt);
            }
        });

        btnDeff.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/images/iconbutton/DeffenseButton.png"))); // NOI18N
        btnDeff.setBorder(javax.swing.BorderFactory.createTitledBorder("DEFFENSE"));
        btnDeff.setPreferredSize(new java.awt.Dimension(120, 40));
        btnDeff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeffActionPerformed(evt);
            }
        });

        PlayerHP.setText("HP Kamu : ");
        PlayerArmor.setText("Armor : ");

        PlayerHP1.setText("Monster HP :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(191, 191, 191)
                .addComponent(btnAttck, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(150, 150, 150)
                .addComponent(btnDeff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(178, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(PlayerHP)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PlayerHP1)
                .addGap(84, 84, 84))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PlayerHP)
                    .addComponent(PlayerArmor)
                    .addComponent(PlayerHP1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 294, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAttck, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeff, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(148, 148, 148))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeffActionPerformed
        if (player == null || monster == null) return;

        performPlayerAction(false);
        updateHpLabels();

        if (finished) {
            if (mainFrame != null) {
                mainFrame.showPanel(new ui.map.mapLevel6(mainFrame));
            }
        }
    }//GEN-LAST:event_btnDeffActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel PlayerHP;
    private javax.swing.JLabel PlayerArmor;
    private javax.swing.JLabel PlayerHP1;
    private javax.swing.JButton btnAttck;
    private javax.swing.JButton btnDeff;
    // End of variables declaration//GEN-END:variables

    private void updateHpLabels() {
        final String pText = (player != null) ? "HP Kamu: " + player.getHp() : "HP Kamu: -";
        final String mText = (monster != null) ? "HP " + monster.getName() + ": " + monster.getHp() : "HP Monster: -";
        final String aText = (player != null) ? "Armor: " + (player.getEquippedArmor() != null ? player.getEquippedArmor().getName() : "-") : "Armor: -";
        if (javax.swing.SwingUtilities.isEventDispatchThread()) {
            PlayerHP.setText(pText);
            PlayerArmor.setText(aText);
            PlayerHP1.setText(mText);
            PlayerHP.revalidate(); PlayerHP.repaint();
            PlayerArmor.revalidate(); PlayerArmor.repaint();
            PlayerHP1.revalidate(); PlayerHP1.repaint();
        } else {
            javax.swing.SwingUtilities.invokeLater(() -> {
                PlayerHP.setText(pText);
                PlayerArmor.setText(aText);
                PlayerHP1.setText(mText);
                PlayerHP.revalidate(); PlayerHP.repaint();
                PlayerArmor.revalidate(); PlayerArmor.repaint();
                PlayerHP1.revalidate(); PlayerHP1.repaint();
            });
        }
    }

    private void btnAttckActionPerformed(java.awt.event.ActionEvent evt) {
        if (player == null || monster == null) return;

        performPlayerAction(true);
        updateHpLabels();

        if (finished) {
            if (mainFrame != null) {
                mainFrame.showPanel(new ui.map.mapLevel1(mainFrame));
            }
        }
    }

    private void performPlayerAction(boolean attack) {
        if (finished) return;

        boolean monsterAttack = rand.nextBoolean();

        if (attack && monsterAttack) {
            monster.setHp(monster.getHp() - player.getAttack());
            applyDamageToPlayer(monster.getAttack());
        } else if (attack && !monsterAttack) {
            monster.setHp(monster.getHp() - player.getAttack());
        } else if (!attack && monsterAttack) {
            applyDamageToPlayer(monster.getAttack() / 2);
        } else {
            // both defend; nothing happens
        }

        if (!player.isAlive() || !monster.isAlive()) {
            finished = true;
            if (player.isAlive()) {
                // Only restore HP when the entire fight finishes (after boss is defeated)
                if (stage != 1) {
                    player.restoreFullHp();
                    updateHpLabels();
                }

                java.util.List<Object> drops = DropItemAfterDefeatMonster.dropItems(player);
                if (drops != null && !drops.isEmpty()) {
                    String[] options = new String[drops.size()];
                    for (int i = 0; i < drops.size(); i++) {
                        Object it = drops.get(i);
                        if (it instanceof model.Weapon) {
                            model.Weapon w = (model.Weapon) it;
                            options[i] = "Weapon: " + w.getName() + " (+" + w.getAttack() + " atk)";
                        } else if (it instanceof model.Armor) {
                            model.Armor a = (model.Armor) it;
                            options[i] = "Armor: " + a.getName() + " (+" + a.getDefense() + " HP)";
                        } else {
                            options[i] = it.toString();
                        }
                    }
                    int choice = JOptionPane.showOptionDialog(this, "Pilih satu item yang ingin kamu ambil:", "Item Drop",
                            JOptionPane.DEFAULT_OPTION, JOptionPane.PLAIN_MESSAGE, null, options, options[0]);

                    if (choice >= 0 && choice < drops.size()) {
                        Object chosen = drops.get(choice);
                        player.addItem(chosen);
                        if (chosen instanceof model.Weapon) {
                            model.Weapon w = (model.Weapon) chosen;
                            JOptionPane.showMessageDialog(this, "Mendapatkan " + w.getName() + "! Masuk inventory.");
                        } else if (chosen instanceof model.Armor) {
                            model.Armor a = (model.Armor) chosen;
                            JOptionPane.showMessageDialog(this, "Mendapatkan " + a.getName() + "! Masuk inventory.");
                        } else {
                            JOptionPane.showMessageDialog(this, "Mendapatkan item! Masuk inventory.");
                        }
                        updateHpLabels();
                    }
                }

                if (stage == 1) {
                    stage = 2;
                    finished = false;
                    monster = new Monster("Boss Level 6", 220, 26, 18);
                    JOptionPane.showMessageDialog(this, "Keroco dikalahkan! Boss muncul!");
                    updateHpLabels();
                } else {
                    if (mainFrame != null) {
                        mainFrame.showPanel(new ui.map.mapLevel6(mainFrame));
                    }
                }
            }
            else {
                // player lost
                player.setMaxHp(100);
                player.restoreFullHp();
                updateHpLabels();
                JOptionPane.showMessageDialog(this, "Kamu kalah. HP direset menjadi 100.", "Kalah", JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }

    private void applyDamageToPlayer(int dmg) {
        if (player == null || dmg <= 0) return;
        // armor/defense removed, apply damage directly
        player.takeDamage(dmg);
    }

}
