/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.fight;

import controllers.InventoryController;
import main.mainFrame;
import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
import logic.DropItemAfterDefeatMonster;
import java.util.Random;
import model.Player;
import model.Monster;

public class FightLevel6 extends javax.swing.JPanel {

    private mainFrame mainFrame;
    private Player player;
    private Monster monster;
    private boolean finished = false;
    private Random rand = new Random();
    private int stage = 1; // 1 = Keroco, 2 = Boss
    private InventoryController inventoryController = new InventoryController();

    /**
     * Creates new form FightLevel1
     */
    public FightLevel6(mainFrame mainFrame, Player player, Monster monster) {
        this.mainFrame = mainFrame;
        this.player = player;
        this.monster = monster;
        initComponents();

        this.finished = false;
        updateHpLabels();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PlayerHP = new javax.swing.JLabel();
        PlayerArmor = new javax.swing.JLabel();
        PlayerHP1 = new javax.swing.JLabel();
        btnAttck = new javax.swing.JButton();
        btnDeff = new javax.swing.JButton();
        bgKroco = new javax.swing.JLabel();
        bgBos = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PlayerHP.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        PlayerHP.setForeground(new java.awt.Color(255, 255, 255));
        PlayerHP.setText("HP Kamu : ");
        add(PlayerHP, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, -1, -1));

        PlayerArmor.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        PlayerArmor.setForeground(new java.awt.Color(255, 255, 255));
        PlayerArmor.setText("Armor : ");
        add(PlayerArmor, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, -1, -1));

        PlayerHP1.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        PlayerHP1.setForeground(new java.awt.Color(255, 255, 255));
        PlayerHP1.setText("Monster HP :");
        add(PlayerHP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 50, -1, -1));

        btnAttck.setBorder(javax.swing.BorderFactory.createTitledBorder("ATTACK"));
        btnAttck.setBorderPainted(false);
        btnAttck.setContentAreaFilled(false);
        btnAttck.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAttck.setPreferredSize(new java.awt.Dimension(120, 40));
        btnAttck.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAttckMouseClicked(evt);
            }
        });
        btnAttck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAttckActionPerformed(evt);
            }
        });
        add(btnAttck, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 475, 110, 110));

        btnDeff.setBorder(javax.swing.BorderFactory.createTitledBorder("DEFFENSE"));
        btnDeff.setBorderPainted(false);
        btnDeff.setContentAreaFilled(false);
        btnDeff.setPreferredSize(new java.awt.Dimension(120, 40));
        btnDeff.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDeffMouseClicked(evt);
            }
        });
        btnDeff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeffActionPerformed(evt);
            }
        });
        add(btnDeff, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 450, 80, 80));

        bgKroco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/images/fightbg/LEVEL 6 MINI BOSS.png"))); // NOI18N
        add(bgKroco, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        bgBos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/images/fightbg/LEVEL 6(1).png"))); // NOI18N
        add(bgBos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeffActionPerformed
        mainFrame.playSFX("C:\\Users\\Dhenis\\Documents\\NetBeansProjects\\Kyojin_Gemu\\src\\resource\\sounds\\Deff.wav");
        if (player == null || monster == null) return;

        performPlayerAction(false);
        updateHpLabels();

        if (finished) {
            if (mainFrame != null) {
                mainFrame.showPanel(new ui.map.mapPanel(mainFrame));
            }
        }
    }//GEN-LAST:event_btnDeffActionPerformed

    private void btnAttckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAttckActionPerformed
        // TODO add your handling code here:
        mainFrame.playSFX("C:\\Users\\Dhenis\\Documents\\NetBeansProjects\\Kyojin_Gemu\\src\\resource\\sounds\\Deff.wav");
                if (player == null || monster == null) return;

        performPlayerAction(true);
        updateHpLabels();

        if (finished) {
            if (mainFrame != null) {
                mainFrame.showPanel(new ui.map.mapPanel(mainFrame));
            }
        }
    }//GEN-LAST:event_btnAttckActionPerformed

    private void btnAttckMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAttckMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAttckMouseClicked

    private void btnDeffMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeffMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeffMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel PlayerArmor;
    private javax.swing.JLabel PlayerHP;
    private javax.swing.JLabel PlayerHP1;
    private javax.swing.JLabel bgBos;
    private javax.swing.JLabel bgKroco;
    private javax.swing.JButton btnAttck;
    private javax.swing.JButton btnDeff;
    // End of variables declaration//GEN-END:variables

    private void updateHpLabels() {
        final String pText = (player != null) ? "HP Kamu: " + player.getHp() : "HP Kamu: -";
        final String mText = (monster != null) ? "HP " + monster.getName() + ": " + monster.getHp() : "HP Monster: -";
        final String aText = (player != null) ? "Armor: " + (player.getEquippedArmor() != null ? player.getEquippedArmor().getName() : "-") : "Armor: -";
        if (javax.swing.SwingUtilities.isEventDispatchThread()) {
            PlayerHP.setText(pText);
            PlayerArmor.setText(aText);
            PlayerHP1.setText(mText);
            PlayerHP.revalidate(); PlayerHP.repaint();
            PlayerArmor.revalidate(); PlayerArmor.repaint();
            PlayerHP1.revalidate(); PlayerHP1.repaint();
        } else {
            javax.swing.SwingUtilities.invokeLater(() -> {
                PlayerHP.setText(pText);
                PlayerArmor.setText(aText);
                PlayerHP1.setText(mText);
                PlayerHP.revalidate(); PlayerHP.repaint();
                PlayerArmor.revalidate(); PlayerArmor.repaint();
                PlayerHP1.revalidate(); PlayerHP1.repaint();
            });
        }
    }

    private void performPlayerAction(boolean attack) {
        if (finished) return;

        boolean monsterAttack = rand.nextBoolean();

        if (attack && monsterAttack) {
            monster.setHp(monster.getHp() - player.getAttack());
            applyDamageToPlayer(monster.getAttack());
        } else if (attack && !monsterAttack) {
            monster.setHp(monster.getHp() - player.getAttack());
        } else if (!attack && monsterAttack) {
            applyDamageToPlayer(monster.getAttack() / 2);
        } else {
            // both defend; nothing happens
        }

        if (!player.isAlive() || !monster.isAlive()) {
            finished = true;
            if (player.isAlive()) {
                // Only restore HP when the entire fight finishes (after boss is defeated)
                if (stage != 1) {
                    player.restoreFullHp();
                    updateHpLabels();
                }

                java.util.List<Object> drops = DropItemAfterDefeatMonster.dropItems(player);
                if (drops != null && !drops.isEmpty()) {
                    String[] options = new String[drops.size()];
                    for (int i = 0; i < drops.size(); i++) {
                        Object it = drops.get(i);
                        if (it instanceof model.Weapon) {
                            model.Weapon w = (model.Weapon) it;
                            options[i] = "Weapon: " + w.getName() + " (+" + w.getAttack() + " atk)";
                        } else if (it instanceof model.Armor) {
                            model.Armor a = (model.Armor) it;
                            options[i] = "Armor: " + a.getName() + " (+" + a.getDefense() + " HP)";
                        } else {
                            options[i] = it.toString();
                        }
                    }
                    int choice = JOptionPane.showOptionDialog(this, "Pilih satu item yang ingin kamu ambil:", "Item Drop",
                            JOptionPane.DEFAULT_OPTION, JOptionPane.PLAIN_MESSAGE, null, options, options[0]);

                    if (choice >= 0 && choice < drops.size()) {
                        Object chosen = drops.get(choice);

                        // 1. Simpan ke database
                        boolean saved = inventoryController.addItemToInventory(player, chosen);

                        if (saved) {
                            // 2. Masukkan ke Player object
                            player.addItem(chosen);

                            // 3. Notifikasi
                            if (chosen instanceof model.Weapon) {
                                model.Weapon w = (model.Weapon) chosen;
                                JOptionPane.showMessageDialog(this,
                                    "Mendapatkan " + w.getName() + "! Masuk inventory.");
                            } else if (chosen instanceof model.Armor) {
                                model.Armor a = (model.Armor) chosen;
                                JOptionPane.showMessageDialog(this,
                                    "Mendapatkan " + a.getName() + "! Masuk inventory.");
                            }
                        } else {
                            JOptionPane.showMessageDialog(this,
                                "Gagal menyimpan item ke database!",
                                "Error",
                                JOptionPane.ERROR_MESSAGE);
                        }
                        updateHpLabels();
                    }
                }
                    
                //Icon Bos Dialog
                var imagePath = "/resource/images/iconbutton/Bos6.png";
                ImageIcon bosIcon = new ImageIcon(getClass().getResource(imagePath));
                
                if (stage == 1) {
                    stage = 2;
                    finished = false;
                    monster = new Monster("Prince Aurelius", 300, 30, 20);
                    JOptionPane.showMessageDialog(this, "Kuat juga kau","Prince Aurelius",JOptionPane.INFORMATION_MESSAGE,bosIcon);
                    updateHpLabels();
                    bgKroco.setVisible(false);
                    bgBos.setVisible(true);
                } else {
                    if (mainFrame != null) {
                        JOptionPane.showMessageDialog(this, "Selamat! Kamu mengalahkan Prince Aurelius");
                        mainFrame.showPanel(new ui.map.mapPanel(mainFrame));
                    }
                }
            }
            else {
                // player lost
                mainFrame.stopMusic();
                mainFrame.playMusic("C:\\Users\\Dhenis\\Documents\\NetBeansProjects\\Kyojin_Gemu\\src\\resource\\sounds\\MUSIC IDLE.wav");
                player.setMaxHp(100);
                // reapply armor bonus if player has armor equipped
                if (player.getEquippedArmor() != null) {
                    player.addMaxHp(player.getEquippedArmor().getDefense());
                }
                player.restoreFullHp();
                updateHpLabels();
                JOptionPane.showMessageDialog(this, "Kamu kalah", "Kalah", JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }

    private void applyDamageToPlayer(int dmg) {
        if (player == null || dmg <= 0) return;
        // armor/defense removed, apply damage directly
        player.takeDamage(dmg);
    }

}
