/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.auth;

/**
 *
 * @author Dhenis
 */
import controllers.AuthControllers;
import javax.swing.JOptionPane;
import main.mainFrame;
import ui.menu.menuPanel;
public class registerPage extends javax.swing.JPanel {

    /**
     * Creates new form registerPage
     */
    private mainFrame mainFrame;
    public registerPage(mainFrame mainFrame) {
        initComponents();
        this.mainFrame = mainFrame;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtUser = new javax.swing.JTextField();
        txtPswd = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtPswd1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnRegis = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtUser.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        txtUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserActionPerformed(evt);
            }
        });
        add(txtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(303, 188, 197, 32));

        txtPswd.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        txtPswd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPswdActionPerformed(evt);
            }
        });
        add(txtPswd, new org.netbeans.lib.awtextra.AbsoluteConstraints(303, 248, 197, 32));

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Username");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(303, 166, -1, -1));

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Password");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(303, 226, -1, -1));

        txtPswd1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        txtPswd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPswd1ActionPerformed(evt);
            }
        });
        add(txtPswd1, new org.netbeans.lib.awtextra.AbsoluteConstraints(303, 308, 197, 32));

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Confirm Password");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(303, 286, -1, -1));

        btnRegis.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        btnRegis.setText("Register");
        btnRegis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisActionPerformed(evt);
            }
        });
        add(btnRegis, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 360, 98, 36));

        jButton1.setText("Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 360, 98, 36));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/images/background/UI BACKGROUND.jpg"))); // NOI18N
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void txtUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserActionPerformed

    private void txtPswdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPswdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPswdActionPerformed

    private void txtPswd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPswd1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPswd1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        mainFrame.showPanel(new loginPage(mainFrame));
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnRegisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisActionPerformed
        // TODO add your handling code here:
        
        String userName = txtUser.getText().trim();
        String pwd = txtPswd.getText().trim();
        String confirPwd = txtPswd1.getText().trim();
        
        if (userName.isEmpty() || pwd.isEmpty() || confirPwd.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Semue field Wajib diIsi","Error",JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (!pwd.equals(confirPwd)) {
            JOptionPane.showMessageDialog(this, "Password dan confirm Password Harus sama!","error",JOptionPane.ERROR_MESSAGE);
            return;
        }
        AuthControllers auth = new AuthControllers();
        boolean success = auth.register(userName, pwd);
        
        if (success) {
            JOptionPane.showMessageDialog(this, 
                    "Register Berhasil! ","Sukses",JOptionPane.INFORMATION_MESSAGE);
            mainFrame.showPanel(new loginPage(mainFrame));
        }else{
            JOptionPane.showMessageDialog(this, 
                    "Register Gagal! ","Eroor",JOptionPane.ERROR_MESSAGE); 
        }
    }//GEN-LAST:event_btnRegisActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegis;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtPswd;
    private javax.swing.JTextField txtPswd1;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
