/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.map;

/**
 *
 * @author Dhenis
 */
import main.mainFrame;
import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
import model.Player;
import model.Monster;

public class mapLevel2 extends javax.swing.JPanel {
    /**
     * Creates new form mapLevel1
     */
    private mainFrame mainFrame;
    private Player player;
    private Monster monster;
    // BattleController removed; fight handled in dedicated fight panel
    
    public mapLevel2(mainFrame mainFrame) {
        initComponents();
        this.mainFrame = mainFrame;
        // obtain player from mainFrame (if set)
        this.player = (mainFrame != null) ? mainFrame.getPlayer() : null;
        // initialize monster for this level
        this.monster = new Monster("Orc", 80, 12, 6);

    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnback = new javax.swing.JButton();
        btnFightt = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnback.setText("Back");
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });
        add(btnback, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 16, -1, -1));

        btnFightt.setText("Fight!");
        btnFightt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFighttActionPerformed(evt);
            }
        });
        add(btnFightt, new org.netbeans.lib.awtextra.AbsoluteConstraints(315, 485, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/images/fightbg/LEVEL 2.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        // TODO add your handling code here:
        mainFrame.showPanel(new mapPanel(mainFrame));
    }//GEN-LAST:event_btnbackActionPerformed

    private void btnFighttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFighttActionPerformed
        // TODO add your handling code here:
        // Ensure we have a player instance
        if (this.player == null && this.mainFrame != null) {
            this.player = this.mainFrame.getPlayer();
        }

        if (this.player == null) {
            JOptionPane.showMessageDialog(this, "Player not initialized. Please login first.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (player.getHighestUnlockedLevel() < 2) {
             JOptionPane.showMessageDialog(
               this,
               "Level 2 masih terkunci!\nSelesaikan Level 1 terlebih dahulu.",
               "Level Terkunci",
               JOptionPane.WARNING_MESSAGE
           );
           return;
        }

        // Level-specific dialog content
        String message = "Kamu memasuki level 2. Di hadapanmu muncul seekor Orc yang lebih besar. Siap untuk bertarung?";

        // Ask for confirmation to start the fight
        int confirm = JOptionPane.showConfirmDialog(this, message, "Encounter - Level 2", JOptionPane.YES_NO_OPTION);
        if (confirm != JOptionPane.YES_OPTION) {
            return;
        }

        // After dialog is closed, switch to the dedicated fight panel (FightLevel1)
        if (this.mainFrame != null) {
            // create first-stage monster (Keroco) for fight
            Monster fightMonster = new Monster("Orc", 50, 6, 2);
            ui.fight.FightLevel2 fightPanel = new ui.fight.FightLevel2(this.mainFrame, this.player, fightMonster);
            this.mainFrame.showPanel(fightPanel);
        } else {
            // This should not happen in normal flow; inform and abort
            JOptionPane.showMessageDialog(this, "Unable to start fight: mainFrame not available.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
    }//GEN-LAST:event_btnFighttActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFightt;
    private javax.swing.JButton btnback;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
