/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.map;

/**
 *
 * @author Dhenis
 */
import main.mainFrame;
import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
import model.Player;
import model.Monster;
import ui.menu.*;

public class mapLevel1 extends javax.swing.JPanel {
    /**
     * Creates new form mapLevel1
     */
    private mainFrame mainFrame;
    private Player player;
    private Monster monster;
    // BattleController removed; fight handled in dedicated fight panel
    
    public mapLevel1(mainFrame mainFrame) {
        initComponents();
        this.mainFrame = mainFrame;
        // obtain player from mainFrame (if set)
        this.player = (mainFrame != null) ? mainFrame.getPlayer() : null;

    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnInventory = new javax.swing.JButton();
        btnback = new javax.swing.JButton();
        btnFightt = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnInventory.setBackground(new java.awt.Color(0,0,0,0));
        btnInventory.setBorder(javax.swing.BorderFactory.createMatteBorder(
            0, 1, 0, 1,
            new java.awt.Color(230,230,230)
        ));
        btnInventory.setBorderPainted(false);
        btnInventory.setContentAreaFilled(false);
        btnInventory.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnInventory.setMaximumSize(new java.awt.Dimension(72, 10));
        btnInventory.setMinimumSize(new java.awt.Dimension(72, 10));
        btnInventory.setPreferredSize(new java.awt.Dimension(72, 10));
        btnInventory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnInventoryMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnInventoryMouseExited(evt);
            }
        });
        btnInventory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInventoryActionPerformed(evt);
            }
        });
        add(btnInventory, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 460, 90, 90));

        btnback.setText("Back");
        btnback.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });
        add(btnback, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        btnFightt.setActionCommand("");
        btnFightt.setBorderPainted(false);
        btnFightt.setContentAreaFilled(false);
        btnFightt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFightt.setFocusable(false);
        btnFightt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFighttActionPerformed(evt);
            }
        });
        add(btnFightt, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 3, 800, 600));

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Klik dimana saja untuk bertarung!");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 540, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/images/fightbg/LEVEL 1.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        // TODO add your handling code here:
        mainFrame.showPanel(new mapPanel(mainFrame));
    }//GEN-LAST:event_btnbackActionPerformed

    private void btnFighttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFighttActionPerformed
        // TODO add your handling code here:
        // Ensure we have a player instance
        if (this.player == null && this.mainFrame != null) {
            this.player = this.mainFrame.getPlayer();
        }

        if (this.player == null) {
            JOptionPane.showMessageDialog(this, "Player not initialized. Please login first.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Level-specific dialog content
        String message = "Hei Kau, jika ingin lewat, Kalahkan aku dulu!";
        String message2 = "Oke, mari bertarung";
        
        JOptionPane.showMessageDialog(this, message, "Wolf of Sumatra",JOptionPane.INFORMATION_MESSAGE);
        JOptionPane.showMessageDialog(this, message2, player.getName() ,JOptionPane.INFORMATION_MESSAGE);

        // After dialog is closed, switch to the dedicated fight panel (FightLevel1)
        if (this.mainFrame != null) {
            // create first-stage monster (Keroco) for fight
            Monster fightMonster = new Monster("Wolf", 70, 6, 2);
            ui.fight.FightLevel1 fightPanel = new ui.fight.FightLevel1(this.mainFrame, this.player, fightMonster);
            this.mainFrame.showPanel(fightPanel);
        } else {
            // This should not happen in normal flow; inform and abort
            JOptionPane.showMessageDialog(this, "Unable to start fight: mainFrame not available.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
    }//GEN-LAST:event_btnFighttActionPerformed

    private void btnInventoryMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInventoryMouseEntered
        // TODO add your handling code here:
        btnInventory.setBorderPainted(true);
    }//GEN-LAST:event_btnInventoryMouseEntered

    private void btnInventoryMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInventoryMouseExited
        // TODO add your handling code here:
        btnInventory.setBorderPainted(false);
    }//GEN-LAST:event_btnInventoryMouseExited

    private void btnInventoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInventoryActionPerformed
        Player p = (mainFrame != null) ? mainFrame.getPlayer() : null;
        if (p == null) {
            JOptionPane.showMessageDialog(this, "Player belum diset. Silakan login terlebih dahulu.", "Inventory", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        // Open the Inventory UI (InventoryPanel removed; logic moved to Inventory)
        if (mainFrame != null) {
            mainFrame.showPanel(new Inventory(mainFrame));
        }
    }//GEN-LAST:event_btnInventoryActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFightt;
    private javax.swing.JButton btnInventory;
    private javax.swing.JButton btnback;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
