/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.menu;

/**
 *
 * @author Dhenis
 */
import main.mainFrame;
import javax.swing.*;
import java.awt.event.*;
import model.Player;
import ui.map.mapPanel;

public class menuPanel extends javax.swing.JPanel {

    private mainFrame mainFrame;
    private Player player;
    private JButton btnStart;
    
    public menuPanel(mainFrame mainFrame) {
        initComponents();
        this.mainFrame = mainFrame;
    }
    
    public void setPlayer(Player player) {
        this.player = player;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnNew = new javax.swing.JButton();
        btnOption = new javax.swing.JButton();
        btnInventory = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnNew.setFont(new java.awt.Font("Mistral", 1, 36)); // NOI18N
        btnNew.setBorder(null);
        btnNew.setBorderPainted(false);
        btnNew.setContentAreaFilled(false);
        btnNew.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });
        add(btnNew, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 370, 100, 50));

        btnOption.setFont(new java.awt.Font("Mistral", 1, 36)); // NOI18N
        btnOption.setBorder(null);
        btnOption.setBorderPainted(false);
        btnOption.setContentAreaFilled(false);
        btnOption.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOptionActionPerformed(evt);
            }
        });
        add(btnOption, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 420, 80, 40));

        btnInventory.setBackground(new java.awt.Color(0,0,0,0));
        btnInventory.setBorder(null);
        btnInventory.setBorderPainted(false);
        btnInventory.setContentAreaFilled(false);
        btnInventory.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnInventory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInventoryActionPerformed(evt);
            }
        });
        add(btnInventory, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 470, 100, 40));

        btnExit.setFont(new java.awt.Font("Mistral", 1, 36)); // NOI18N
        btnExit.setBorder(null);
        btnExit.setBorderPainted(false);
        btnExit.setContentAreaFilled(false);
        btnExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 520, 100, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/images/background/UI MENU EXIT.png"))); // NOI18N
        jLabel2.setMaximumSize(new java.awt.Dimension(800, 600));
        jLabel2.setMinimumSize(new java.awt.Dimension(800, 600));
        jLabel2.setPreferredSize(new java.awt.Dimension(800, 600));
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));
    }// </editor-fold>//GEN-END:initComponents

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        // TODO add your handling code here:
        mainFrame.showPanel(new storyPanel(mainFrame));
    }//GEN-LAST:event_btnNewActionPerformed

    private void btnOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOptionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnOptionActionPerformed

    private void btnInventoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInventoryActionPerformed
        Player p = (mainFrame != null) ? mainFrame.getPlayer() : null;
        if (p == null) {
            JOptionPane.showMessageDialog(this, "Player belum diset. Silakan login terlebih dahulu.", "Inventory", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        // Open the Inventory UI (InventoryPanel removed; logic moved to Inventory)
        if (mainFrame != null) {
            mainFrame.showPanel(new Inventory(mainFrame));
        }
    }//GEN-LAST:event_btnInventoryActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExitActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnInventory;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnOption;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
