/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.menu;

/**
 *
 * @author Dhenis
 */
import main.mainFrame;
import javax.swing.*;
import java.awt.event.*;
import model.Player;
import ui.map.mapPanel;
import ui.story.*;

public class menuContinuePanel extends javax.swing.JPanel {

    private mainFrame mainFrame;
    private Player player;
    private JButton btnStart;
    
    public menuContinuePanel(mainFrame mainFrame) {
        initComponents();
        this.mainFrame = mainFrame;
    }
    
    public void setPlayer(Player player) {
        this.player = player;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCredit = new javax.swing.JButton();
        btnContinue = new javax.swing.JButton();
        btnOption = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCredit.setFont(new java.awt.Font("Mistral", 1, 36)); // NOI18N
        btnCredit.setBorderPainted(false);
        btnCredit.setContentAreaFilled(false);
        btnCredit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCredit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCreditMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCreditMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCreditMouseExited(evt);
            }
        });
        btnCredit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreditActionPerformed(evt);
            }
        });
        add(btnCredit, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 561, 25, 25));

        btnContinue.setFont(new java.awt.Font("Mistral", 1, 36)); // NOI18N
        btnContinue.setBorder(javax.swing.BorderFactory.createMatteBorder(
            0, 1, 0, 1,
            new java.awt.Color(230,230,230)
        ));
        btnContinue.setBorderPainted(false);
        btnContinue.setContentAreaFilled(false);
        btnContinue.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnContinue.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnContinueMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnContinueMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnContinueMouseExited(evt);
            }
        });
        btnContinue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinueActionPerformed(evt);
            }
        });
        add(btnContinue, new org.netbeans.lib.awtextra.AbsoluteConstraints(361, 350, 78, 15));

        btnOption.setFont(new java.awt.Font("Mistral", 1, 36)); // NOI18N
        btnOption.setBorder(javax.swing.BorderFactory.createMatteBorder(
            0, 1, 0, 1,
            new java.awt.Color(230,230,230)
        ));
        btnOption.setBorderPainted(false);
        btnOption.setContentAreaFilled(false);
        btnOption.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnOption.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnOptionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnOptionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnOptionMouseExited(evt);
            }
        });
        btnOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOptionActionPerformed(evt);
            }
        });
        add(btnOption, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 381, 60, 15));

        btnExit.setFont(new java.awt.Font("Mistral", 1, 36)); // NOI18N
        btnExit.setBorder(javax.swing.BorderFactory.createMatteBorder(
            0, 1, 0, 1,
            new java.awt.Color(230,230,230)
        ));
        btnExit.setBorderPainted(false);
        btnExit.setContentAreaFilled(false);
        btnExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnExitMouseExited(evt);
            }
        });
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 413, 40, 15));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/images/background/UI MENU CONTINUE.png"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));
    }// </editor-fold>//GEN-END:initComponents

    private void btnContinueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinueActionPerformed
        // TODO add your handling code here:
        mainFrame.playSFX("C:\\Users\\Dhenis\\Documents\\NetBeansProjects\\Kyojin_Gemu\\src\\resource\\sounds\\CLICK SFX.wav");
        mainFrame.showPanel(new mapPanel(mainFrame));
    }//GEN-LAST:event_btnContinueActionPerformed

    private void btnOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOptionActionPerformed
        // TODO add your handling code here:
        mainFrame.playSFX("C:\\Users\\Dhenis\\Documents\\NetBeansProjects\\Kyojin_Gemu\\src\\resource\\sounds\\CLICK SFX.wav");
        mainFrame.showPanel(new settingPanel(mainFrame));
    }//GEN-LAST:event_btnOptionActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        mainFrame.playSFX("C:\\Users\\Dhenis\\Documents\\NetBeansProjects\\Kyojin_Gemu\\src\\resource\\sounds\\CLICK SFX.wav");
        int pilihan = JOptionPane.showConfirmDialog(this,
                "Apakah anda yakin ingin Keluar?", "Exit", 
                JOptionPane.YES_NO_OPTION);
        if (pilihan == JOptionPane.YES_OPTION) {
            System.exit(0);}
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnContinueMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnContinueMouseEntered
        // TODO add your handling code here:
        btnContinue.setBorderPainted(true);
        mainFrame.playSFX("C:\\Users\\Dhenis\\Documents\\NetBeansProjects\\Kyojin_Gemu\\src\\resource\\sounds\\HOVER SFX.wav");
    }//GEN-LAST:event_btnContinueMouseEntered

    private void btnOptionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOptionMouseEntered
        // TODO add your handling code here:
        btnOption.setBorderPainted(true);
        mainFrame.playSFX("C:\\Users\\Dhenis\\Documents\\NetBeansProjects\\Kyojin_Gemu\\src\\resource\\sounds\\HOVER SFX.wav");
    }//GEN-LAST:event_btnOptionMouseEntered

    private void btnExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseEntered
        // TODO add your handling code here:
        btnExit.setBorderPainted(true);
        mainFrame.playSFX("C:\\Users\\Dhenis\\Documents\\NetBeansProjects\\Kyojin_Gemu\\src\\resource\\sounds\\HOVER SFX.wav");
    }//GEN-LAST:event_btnExitMouseEntered

    private void btnContinueMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnContinueMouseExited
        // TODO add your handling code here:
        btnContinue.setBorderPainted(false);
    }//GEN-LAST:event_btnContinueMouseExited

    private void btnOptionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOptionMouseExited
        // TODO add your handling code here:
        btnOption.setBorderPainted(false);
    }//GEN-LAST:event_btnOptionMouseExited

    private void btnExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseExited
        // TODO add your handling code here:
        btnExit.setBorderPainted(false);
    }//GEN-LAST:event_btnExitMouseExited

    private void btnCreditMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCreditMouseEntered
        // TODO add your handling code here:
        mainFrame.playSFX("C:\\Users\\Dhenis\\Documents\\NetBeansProjects\\Kyojin_Gemu\\src\\resource\\sounds\\HOVER SFX.wav");
    }//GEN-LAST:event_btnCreditMouseEntered

    private void btnCreditMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCreditMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCreditMouseExited

    private void btnCreditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreditActionPerformed
        // TODO add your handling code here:
        mainFrame.playSFX("C:\\Users\\Dhenis\\Documents\\NetBeansProjects\\Kyojin_Gemu\\src\\resource\\sounds\\CLICK SFX.wav");
        mainFrame.showPanel(new creditPanel(mainFrame));
    }//GEN-LAST:event_btnCreditActionPerformed

    private void btnCreditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCreditMouseClicked
        // TODO add your handling code here:
        mainFrame.playSFX("C:\\Users\\Dhenis\\Documents\\NetBeansProjects\\Kyojin_Gemu\\src\\resource\\sounds\\CLICK SFX.wav");
    }//GEN-LAST:event_btnCreditMouseClicked

    private void btnContinueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnContinueMouseClicked
        // TODO add your handling code here:
        mainFrame.playSFX("C:\\Users\\Dhenis\\Documents\\NetBeansProjects\\Kyojin_Gemu\\src\\resource\\sounds\\CLICK SFX.wav");
    }//GEN-LAST:event_btnContinueMouseClicked

    private void btnOptionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOptionMouseClicked
        // TODO add your handling code here:
        mainFrame.playSFX("C:\\Users\\Dhenis\\Documents\\NetBeansProjects\\Kyojin_Gemu\\src\\resource\\sounds\\CLICK SFX.wav");
    }//GEN-LAST:event_btnOptionMouseClicked

    private void btnExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseClicked
        // TODO add your handling code here:
        mainFrame.playSFX("C:\\Users\\Dhenis\\Documents\\NetBeansProjects\\Kyojin_Gemu\\src\\resource\\sounds\\CLICK SFX.wav");
    }//GEN-LAST:event_btnExitMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnContinue;
    private javax.swing.JButton btnCredit;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnOption;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
