/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main;

import javax.swing.*;
import java.awt.*;
import java.io.File;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.sound.sampled.FloatControl;
import ui.menu.*;
import model.Player;


public class mainFrame extends javax.swing.JFrame {

    private JPanel currentPanel;
    private Player player;
    private javax.swing.JPanel mainPanel;
    public static Clip clip;
    
    public mainFrame() {
        setTitle("Game Project - JFrame Form");
        initComponents();
        mainPanel = jPanel1;
        showPanel(new startPanel(this));
//        testkoneksi();

    }
    
//    koneksi database
//    private void testkoneksi(){
//        Connection conn = DatabaseConection.getConnection();
//        if (conn != null) {
//            System.out.println("koneksi oke");
//        }else{
//            System.out.println("koneksi gagal");
//        }
//    }
//      Pindah Panel
    
    public void showPanel(JPanel panel) {
        if (mainPanel == null) {
            mainPanel = jPanel1;
        }
        mainPanel.removeAll();
        mainPanel.setLayout(new BorderLayout());
        mainPanel.add(panel, BorderLayout.CENTER);
        mainPanel.revalidate();
        mainPanel.repaint();
    }
    
    public void setPlayer(Player player) {
        this.player = player;
    }
     
    public Player getPlayer() {
        return player;
    }
    
    // Baris 62: Parameter menggunakan 'p' kecil
    public static void playMusic(String filepath) { 
        try {
            // Baris 64: Ubah menjadi 'p' kecil juga agar sama
            
            File file = new File(filepath); 

            AudioInputStream audioStream = AudioSystem.getAudioInputStream(file);
            clip = AudioSystem.getClip();
            clip.open(audioStream);
            FloatControl volume = (FloatControl) clip.getControl(FloatControl.Type.MASTER_GAIN);
        
        // Atur nilai desibel (f di belakang angka berarti tipe data float)
        // 0.0f  = Volume normal (bawaan file)
        // -10.0f = Suara lebih kecil
        // -20.0f = Suara jauh lebih kecil
        // -80.0f = Mute (senyap total)
        volume.setValue(-40.0f); 
            clip.start();
        } catch (Exception e) {
            e.printStackTrace();
        } 
    }
    
    public static void stopMusic() {
    // Periksa apakah clip ada dan sedang berjalan
    if (clip != null && clip.isRunning()) {
        clip.stop();          // Menghentikan suara
        clip.setFramePosition(0); // Mengembalikan durasi ke awal (opsional)
        clip.close();         // Membebaskan memori RAM
    }
}
            
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Game Gaje");
        setResizable(false);
        setSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setMaximumSize(new java.awt.Dimension(800, 600));
        jPanel1.setMinimumSize(new java.awt.Dimension(800, 600));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        String musicIdle = "C:\\Users\\Dhenis\\Documents\\NetBeansProjects\\Kyojin_Gemu\\src\\resource\\sounds\\MUSIC IDLE.wav";
         playMusic(musicIdle);
        /* Create and display the form */
        SwingUtilities.invokeLater(() -> new mainFrame());
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainFrame().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
