/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.story;

/**
 *
 * @author Dhenis
 */

import main.mainFrame;
import ui.map.*;

public class Scene3 extends javax.swing.JPanel {

    /**
     * Creates new form Scene3
     */
    
    private mainFrame mainFrame;
    
    public Scene3(mainFrame mainFrame) {
        initComponents();
        this.mainFrame = mainFrame;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        klik1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        next = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        klik1.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        klik1.setForeground(new java.awt.Color(187, 187, 187));
        klik1.setText("Klik di mana saja untuk lanjut");
        add(klik1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 525, 260, 20));

        jScrollPane1.setEnabled(false);
        jScrollPane1.setFocusable(false);
        jScrollPane1.setPreferredSize(new java.awt.Dimension(140, 90));

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(205, 135, 56));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("SimSun-ExtG", 0, 11)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("Ia melihat semuanya dari kejauhan, terikat oleh ketidakmampuan yang kejam.\nRumah tempat ia belajar arti pulang runtuh menjadi bara.Jalan batu yang \nmengingat setiap langkahnya terbelah dan tenggelam dalam api.Sungai yang\ndulu jernih kini memantulkan langit merah, seolah menolak mengenali dirinya \nsendiri. Tidak ada air mata yang langsung jatuh. Yang muncul lebih dulu \nadalah kehampaan, rongga besar yang menghisap suara, panas, dan rasa.\nTubuhnya tetap berdiri, namun sesuatu di dalam dirinya runtuh bersama desa \nitu. Ketika api mereda dan hanya abu yang tersisa, ia tidak lagi mengenali \ndunia yang membesarkannya.");
        jTextArea1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTextArea1.setPreferredSize(new java.awt.Dimension(459, 112));
        jScrollPane1.setViewportView(jTextArea1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 410, 465, 118));

        next.setToolTipText("");
        next.setBorderPainted(false);
        next.setContentAreaFilled(false);
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });
        add(next, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/images/dialog/SCENE 3 DIALOG.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed
        // TODO add your handling code here:
        mainFrame.showPanel(new mapPanel(mainFrame));
    }//GEN-LAST:event_nextActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel klik1;
    private javax.swing.JButton next;
    // End of variables declaration//GEN-END:variables
}
